### ISSUE TITLE
ng-epoch live not working in Edge/IE

### ISSUE THREAD

**Issue by Hammarskjold** [dainbrump/ng-epoch#10]
Hey,

The "Live" items as shown in http://dainbrump.github.io/ng-epoch/examples doesn't render anything in Edge or IE 11, or 10 or 9 or... you get the point. All works splendid in FF and Chrome.

So Edge blurs out the following over and over again:

TypeError: Unable to get property 'push' of undefined or null reference
   at Anonymous function (http://dainbrump.github.io/ng-epoch/js/vendor/ng-epoch.js:72:21)
   at k.prototype.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js:109:401)
   at k.prototype.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js:112:396)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js:122:462)
   at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js:37:495)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js:41:216)

By frigging around a little we have gotten to get the dashboards to update but then they are all black. Which is not really what we want... and yes, we have played around with the different settings of     <meta http-equiv="X-UA-Compatible" content="IE=edge"> but no luck.

Pretty easy to replicate, head over to the test sample site in Edge and you see nothing for the Live graphs.

//Andreas

**Comment by jordyvaneijk** [comment]
+1, Is there any fix for this already?

**Comment by dainbrump** [comment]
@Hammarskjold @jordyvaneijk Sorry about the delay. I wasn't getting notifications for some odd reason and I haven't had a lot of free time lately due to family. I'll try to take a look at this over the next couple days and see if I can push out an update.

**Comment by Hammarskjold** [comment]
We did get it working by modifying the source, only snag is a black frame around the real time bars. But an official fix would of course be a lot better. I will see if I can dig up the changes.
